---

- name: Install dnsmasq.
  homebrew:
    name: dnsmasq
    state: present

- name: Remove .dev resolver if present.
  file:
    path: /etc/resolver/dev
    state: absent
  become: yes

- name: Configure dnsmasq
  copy:
    src: dnsmasq.conf
    dest: /usr/local/etc/dnsmasq.conf

- name: Create dnsmasq launchctl configuration
  copy:
    src: /usr/local/opt/dnsmasq/homebrew.mxcl.dnsmasq.plist
    dest: /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
    owner: root
  become: yes

- name: Start dnsmasq
  shell: launchctl load /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
  become: yes

- name: Make /etc/resolver
  file:
    path: /etc/resolver
    group: admin
    mode: 0755
    state: directory
  become: yes

- name: Configure dnsmasq to serve *.local
  copy:
    src: resolver.local
    dest: /etc/resolver/local
    owner: root
  become: yes
